### ISSUE TITLE
I see that jaeger-exporter does not configure the jaeger endpoint. Can it collect jaeger metrics?

### ISSUE THREAD

**Issue by Cairry** [ricoberger/jaeger-exporter#46]

**Comment by ricoberger** [comment]
Hi @Cairry, no it doesn't collect Jaeger metrics. The Jaeger Exporter is more a hack for people who do not use the [OpenTelemetry Collector ](https://opentelemetry.io/docs/collector/) to use the [Service Performance Monitoring](https://www.jaegertracing.io/docs/1.37/spm/) feature of Jaeger.

It only listens for all the spans on the Jaeger Kafka topic and generates the same metrics as the OpenTelemetry Collector.

**Comment by Cairry** [comment]
OK, thank you. I think your exporter is very useful for me. I also hope to analyze the API request processing time in Jaeger's service performance monitoring. Can I ask more about this? Where does the data on the Kafka topic come from?

**Comment by Cairry** [comment]
Oh! Sorry, I see. Kafka is used as the backend storage for Jaeger, and data can be processed from here.

**Comment by ricoberger** [comment]
Yes the exporter only works when Jaeger is used with Kafka as shown in the following picture:

![architecture-v2](https://github.com/user-attachments/assets/ae9fc6f6-8f78-4c4f-bcb2-ca213b12319c)

The exporter then listens on the same topic as the Jaeger Ingester to generate the metrics.

**Comment by Cairry** [comment]
OK Thanks, I understand. Can it be used with ElasticSearch?

**Comment by ricoberger** [comment]
The database used for Jaeger doesn't matter, the only requirement is that the Jaeger setup with Kafka is used.

**Comment by Cairry** [comment]
I see that the example extracts and processes data from Kafka. Can it extract data from elasticsearch and expose metrics?

**Comment by ricoberger** [comment]
No, unfortunately this is not possible.

**Comment by ricoberger** [comment]
Hi @Cairry, I would close this issue for now.

If there are other questions please let me know and I can reopen the issue.

**Comment by Cairry** [comment]
ok, thanks!
